[package]
name = "amaic_analyzer"
version.workspace = true
edition.workspace = true

[dependencies]
amaic_core.path = "../amaic_core"
amaic_ast.path = "../amaic_ast"
amaic_lexer.path = "../amaic_lexer"

[lints]
workspace = true
