[package]
name = "amaic_parser"
version.workspace = true
edition.workspace = true

[dependencies]
amaic_lexer.path = "../amaic_lexer"
amaic_core.path = "../amaic_core"
amaic_ast.path = "../amaic_ast"

[lints]
workspace = true
